### ISSUE TITLE
Unable to install on Mibew 3.2.1- Application stopped

### ISSUE THREAD

**Issue by tilkov** [Mibew/geo-ip-plugin#6] opened 2019-01-21 11:21 UTC
OS: Ubuntu 16.04 LTS, Mibew 3.2.1 GeoIP 1.0.2
Environment: PHP 7.0.32-0ubuntu0.16.04.1 PDO/7.0.32-0ubuntu0.16.04.1 pdo_mysql/7.0.32-0ubuntu0.16.04.1 gd/7.0.32-0ubuntu0.16.04.1 curl/7.0.32-0ubuntu0.16.04.1 mbstring/7.0.32-0ubuntu0.16.04.1 

On installing the plugin, /index.php/operator/plugin produces the following error:
PHP message: PHP Warning:  Application stopped because of uncaught exception vierbergenlars\SemVer\SemVerException "Invalid Version: 7.0.32-0ubuntu0.16.04.1 [[7.0.32-0ubuntu0.16.04.1]]

**Comment by faf** [comment] 2019-01-22 07:58
Well, it's not the plugin, it's Mibew itself. The issue is caused by the third party library for semantic versioning.

Please, check the solution from this branch: https://github.com/Mibew/mibew/tree/semver_fix

If it will work for you, it will be included in the upcoming release of Mibew Messenger.

**Comment by tilkov** [comment] 2019-01-22 18:18
Yes, the plug-in can be enabled and used now.
Thank you!

**Comment by faf** [comment] 2019-01-23 07:31
You're welcome.

**Closed as completed by faf** 2019-01-23 07:31 UTC
